package com.rainlove.app

internal object RainLovePreferences {
    const val NAME = "rainlove_settings"
    const val TRIGGER_BPM = "trigger_bpm"
    const val RECOVERY_BPM = "recovery_bpm"
    const val TRIGGER_SECONDS = "trigger_seconds"
    const val RECOVERY_SECONDS = "recovery_seconds"
    const val COOLDOWN_SECONDS = "cooldown_seconds"
    const val DEMO_MODE = "demo_mode"
    const val MUSIC_URI = "music_uri"
    const val MUSIC_NAME = "music_name"
    const val TRIGGER_TARGET = "trigger_target"
    const val BILIBILI_BVID = "bilibili_bvid"
    const val BILIBILI_AUTO_PLAY = "bilibili_auto_play"
    const val BILIBILI_BACKGROUND_DIRECT = "bilibili_background_direct"
    const val EXTERNAL_BACKGROUND_DIRECT = "external_background_direct"
    const val NETEASE_SONG_ID = "netease_song_id"
    const val NETEASE_AUTO_PLAY = "netease_auto_play"
    const val EXTERNAL_LINK = "external_link"
    const val EXTERNAL_PACKAGE = "external_package"
    const val EXTERNAL_AUTO_PLAY = "external_auto_play"
    const val RESUME_ON_BOOT = "resume_on_boot"
    const val MONITORING_DESIRED = "monitoring_desired"
    const val HEART_RATE_TRANSPORT = "heart_rate_transport"
    const val DEVICE_ADDRESS = "device_address"
    const val DEVICE_NAME = "device_name"
    const val PROFILE_NAMES = "profile_names"
}
